### ISSUE TITLE
Switch to python3.6 | Improve code

### ISSUE THREAD

**Issue by sameerkumar18** [sameerkumar18/aztro#12]
Need to migrate the code base to Python 3.6, it's running Python2.7 at the moment!

**Comment by senthilraja112** [comment]
I will do it

**Comment by senthilraja112** [comment]
What is the file name that want to change from python2.7 to python3.6

**Comment by Vaibhav** [comment]
I added a PR, all tests are passing for python 3.6.6 #13

**Comment by sameerkumar18** [comment]
Hey @Vaibhav 
I tried running your code, here are some notes - 
1) `date_range` is empty string
2) There's double backslash in places where apostrophe comes.
3) Can you try removing the spaces towards the ends of the value in the json returned
Here is a screenshot from Postman - https://i.imgur.com/OEyL8Ze.png
Can you please check again?
And btw, seems like tests aren't well written :/

Thanks!

**Comment by Vaibhav** [comment]
Hi @sameerkumar18 

Sorry, I didn't dive into manual testing. I assumed the tests had good coverage. I have fixed the issues you mentioned. Let me know if you find any more bugs.

**Comment by sameerkumar18** [comment]
Awesome work! Thanks @Vaibhav 👍
