### ISSUE TITLE
Cross origin issue - No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by ajaymarathe** [sameerkumar18/aztro#18]
Hi there, 

I am using this API with _`React.js`_ and giving *`cross-origin`* issue, below are the error:-

```
Access to XMLHttpRequest at 'https://aztro.readthedocs.io/en/latest/' (redirected from 'https://aztro.sameerkumar.website/?sign=aries&day=today') from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
I will suggest you to add *`headers`* in your backend.

thanks :)

**Comment by sameerkumar18** [comment]
@ajaymarathe Are you making a POST or a GET request? 
It should be a POST request

**Comment by ajaymarathe** [comment]
> @ajaymarathe Are you making a POST or a GET request?
> It should be a POST request

@sameerkumar18 Yeah it is _`POST`_ request. actually I was hitting _`get`_ request, this is why I getting _`cross-issue`_, but later I read docs and changed that to post and **_it works_**, thanks bro :)
