### ISSUE TITLE
API dont work

### ISSUE THREAD

**Issue by bllhlskr** [sameerkumar18/aztro#24]
im trying to access your api and it connects me to your document website is this api closed? can anybody help me?

**Comment by sameerkumar18** [comment]
Hi @bllhlskr The API looks fine to me
Seems like you are making an HTTP GET request which is intentionally redirected to the http://aztro.readthedocs.io. Instead, you should be making an HTTP POST request to the API endpoint. 
Let me know if that solves the issue

**Comment by bllhlskr** [comment]
im copying this https://aztro.sameerkumar.website/?sign=aries&day=today and paste in my browser search bar it returns your website am i wrong what should i use

**Comment by sameerkumar18** [comment]
It is not intended to work that way. I'd suggest you use cURL/Postman/Hoppscotch for making POST requests 
Check this - https://stackoverflow.com/questions/4797534/how-to-manually-send-http-post-requests-from-firefox-or-chrome-browser

**Comment by bllhlskr** [comment]
okay thank you for your answer and time i will use this to create ios application
