### ISSUE TITLE
Post response does not match expected compatibility

### ISSUE THREAD

**Issue by Idan503** [sameerkumar18/aztro#29]
The API looks great, but there is an issue that makes the usage harder to implement.  

the response value of the `POST` request doesn't match the same compatibility of the sign name given in the parameters.  

For example when using `POST` like this (**Aries** sign): https://aztro.sameerkumar.website?sign=aries&day=today
The response looks like {date_range:..... "compatibility": "**Capricorn**" .....}  
Which is not aries as expected.

**Comment by sameerkumar18** [comment]
Hi @Idan503 The "compatibility" here is in relation to the input sign. So when you pass "Aries" and the compatibility is "Capricon" - It means that Aries would be best compatible today to engage with Capricon.
Hope that helps :)

**Comment by Idan503** [comment]
Oh, I see...
Thank you so much.
