### ISSUE TITLE
Golang API Wrapper

### ISSUE THREAD

**Issue by irfansofyana** [sameerkumar18/aztro#34]
Hi @sameerkumar18, I'm interested to contribute to this project by building the API wrapper in Go. The code is here: https://github.com/irfansofyana/go-aztro-api-wrapper.
Is it possible for me to add this to the website documentation?
Thanks in advance.

**Comment by sameerkumar18** [comment]
Hey @irfansofyana, Great work! 
I'd love to add this to the documentation. Usually, I add it under the API wrappers ([like this](https://github.com/sameerkumar18/aztro#api-wrappers)).
Like NPM, PIP, I suppose there's a package manager for Golang too? If so, could you add your Go package there? ([here's a guide](https://www.digitalocean.com/community/tutorials/how-to-distribute-go-modules)). I'm sure it'll be 10x more convenient for Golang programmers to use it! Thanks!

**Comment by irfansofyana** [comment]
sure @sameerkumar18, I will work on adding documentation to https://pkg.go.dev/std. Will inform you when I have done, thank you!

**Comment by irfansofyana** [comment]
hey @sameerkumar18 here you go: https://pkg.go.dev/github.com/irfansofyana/go-aztro-api-wrapper/aztro, I have published the go-API wrapper there.

**Comment by irfansofyana** [comment]
created a PR to add golnag api wrapper in the README: #35

**Comment by sameerkumar18** [comment]
Excellent work @irfansofyana - I've merged the PR

**Comment by irfansofyana** [comment]
thank you! I'll close this issue
