### ISSUE TITLE
Re-opening issue 16 : 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by chihabhajji** [sameerkumar18/aztro#38]
#16

**Comment by martzro** [comment]
Website the api scrapes from is down with their database connection failing. Having issues as well with nothing returning

**Comment by chihabhajji** [comment]
i havent read the code base, but is there a cron job for caching results of the day ? i mean it makes sense to do it since its only 10 signs and 3 time intervals

**Comment by JamesBrightman** [comment]
This is an issue I am currently running into as well.
